//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEntrada
    {
        public long IdDetalleEntrada { get; set; }
        public int IdEntrada { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Entrada Entrada { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
