//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitaciones()
        {
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int IdHabitacion { get; set; }
        public string NumeroHabitacion { get; set; }
        public int IdTipoHabitacion { get; set; }
        public decimal Tarifa { get; set; }
        public int NumeroPersonas { get; set; }
        public short IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CEstados CEstados { get; set; }
        public virtual CEstados CEstados1 { get; set; }
        public virtual CTipoHabitacion CTipoHabitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
