//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleEntrada = new HashSet<DetalleEntrada>();
            this.DetalleOrdenPago = new HashSet<DetalleOrdenPago>();
            this.DetalleOrdenPago1 = new HashSet<DetalleOrdenPago>();
        }
    
        public int IdProducto { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public int Existencia { get; set; }
        public short IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CEstados CEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntrada> DetalleEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenPago> DetalleOrdenPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenPago> DetalleOrdenPago1 { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
