//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transacciones()
        {
            this.TransaccionesOrdenPago = new HashSet<TransaccionesOrdenPago>();
        }
    
        public long IdTransaccion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string NumeroHabitacion { get; set; }
        public System.DateTime FechaHoraIngreso { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public int TotalDias { get; set; }
        public int NumeroPersonas { get; set; }
        public short IdEstado { get; set; }
        public decimal Total { get; set; }
    
        public virtual CEstados CEstados { get; set; }
        public virtual CEstados CEstados1 { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionesOrdenPago> TransaccionesOrdenPago { get; set; }
    }
}
